source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SAGE' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'AFNetworking', '~> 2.0'
  pod 'FontAwesomeKit', :git => 'https://github.com/PrideChung/FontAwesomeKit.git'
  pod 'SwiftKeychainWrapper', '~> 2.0'
  pod 'BSKeyboardControls', '~> 2.2'
end
